project:
  type: website

website:
  title: "Research Software Engineering - TopoStats Case Study"
  site-url: https://ns-rse.github.io/topostats-showcase
  description: "Quarto RevealJS slides of a case study of the impact Research Software Engineering support has had on the TopoStats software."
